### ISSUE TITLE
龙的天空 评论区

### ISSUE THREAD

**Issue by a76yyyy** [qd-today/templates#101]

**Comment by pooneyy** [comment]
### 更新模板
龙的天空.har

### 更新说明
将龙空签到脚本修改为通过账号密码登录
### 模板备注及说明
原先通过Cookie登录。龙空的Cookie有效期为31天，每个月都需要更新Cookie。
现修改为通过账号密码登录。
### HAR 模板内容

```json
[{"comment":"登录","request":{"method":"POST","url":"https://api.lkong.com/api","headers":[{"name":"Content-Type","value":"application/json"}],"cookies":[],"data":"{\"operationName\": \"Login\",\"variables\": {\"email\": \"{{account}}\",\"password\": \"{{password}}\"},\"query\": \"mutation Login($email: String!, $password: String!) {\\n  login(email: $email, password: $password) {\\n    uid\\n    name\\n    twoWay\\n    serverTime\\n    __typename\\n  }\\n}\"}"},"rule":{"success_asserts":[{"re":"200","from":"status"}],"failed_asserts":[],"extract_variables":[{"name":"cookie","re":"Set-Cookie:(.+?);","from":"header"}]}},{"comment":"签到","request":{"method":"POST","url":"https://api.lkong.com/api","headers":[{"name":"Host","value":"api.lkong.com"},{"name":"Connection","value":"keep-alive"},{"name":"Pragma","value":"no-cache"},{"name":"Cache-Control","value":"no-cache"},{"name":"sec-ch-ua","value":"\"Google Chrome\";v=\"93\", \" Not;A Brand\";v=\"99\", \"Chromium\";v=\"93\""},{"name":"accept","value":"*/*"},{"name":"content-type","value":"application/json"},{"name":"User-Agent","value":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36"},{"name":"sec-ch-ua-platform","value":"\"Windows\""},{"name":"Origin","value":"https://www.lkong.com"},{"name":"Referer","value":"https://www.lkong.com/"},{"name":"Accept-Encoding","value":"gzip, deflate, br"},{"name":"Accept-Language","value":"zh-CN,zh;q=0.9,en;q=0.8"},{"name":"Cookie","value":"{{cookie}}"}],"cookies":[],"data":"{\"variables\":{},\"query\":\"mutation {\\n  punch {\\n    uid\\n    punchday\\n    isPunch\\n    punchhighestday\\n    punchallday\\n    __typename\\n  }\\n}\\n\"}","mimeType":"application/json"},"rule":{"success_asserts":[{"re":"200","from":"status"}],"failed_asserts":[{"re":"\"uid\":0","from":"content"}],"extract_variables":[{"name":"uid","re":"\"uid\":(.+?),\"","from":"content"},{"name":"punchday","re":"\"punchday\":(.+?),\"","from":"content"},{"name":"punchhighestday","re":"\"punchhighestday\":(.+?),\"","from":"content"},{"name":"punchallday","re":"\"punchallday\":(.+?),\"","from":"content"}]}},{"comment":"登出","request":{"method":"POST","url":"https://api.lkong.com/api","headers":[{"name":"Content-Type","value":"application/json"},{"name":"Cookie","value":"{{cookie}}"}],"cookies":[],"data":"{\n    \"variables\": {},\n    \"query\": \"mutation {\\n  logout {\\n    ok\\n    __typename\\n  }\\n}\"\n}"},"rule":{"success_asserts":[{"re":"200","from":"status"}],"failed_asserts":[],"extract_variables":[]}},{"comment":"生成日志","request":{"method":"GET","url":"api://util/string/replace?r=text&t=%C2%A0&p=%C2%A0&s=%E7%94%A8%E6%88%B7ID%E4%B8%BA%EF%BC%9A{{uid|urlencode}}%EF%BC%8C%E5%BD%93%E5%89%8D%E7%AD%BE%E5%88%B0%EF%BC%9A{{punchday|urlencode}}%E5%A4%A9%EF%BC%8C%E6%9C%80%E9%AB%98%E7%AD%BE%E5%88%B0{{punchhighestday|urlencode}}%E5%A4%A9%EF%BC%8C%E6%80%BB%E5%85%B1%E7%AD%BE%E5%88%B0{{punchallday|urlencode}}%E5%A4%A9%E3%80%82","headers":[],"cookies":[]},"rule":{"success_asserts":[{"re":"200","from":"status"}],"failed_asserts":[],"extract_variables":[{"re":".+","from":"content","name":"__log__"}]}}]
```

**Comment by a76yyyy** [comment]
> ### 更新模板
> 龙的天空.har
> 
> ### 更新说明
> 将龙空签到脚本修改为通过账号密码登录
> ### 模板备注及说明
> 原先通过Cookie登录。龙空的Cookie有效期为31天，每个月都需要更新Cookie。
> 现修改为通过账号密码登录。
> ### HAR 模板内容
> 
> ```json
> [{"comment":"登录","request":{"method":"POST","url":"https://api.lkong.com/api","headers":[{"name":"Content-Type","value":"application/json"}],"cookies":[],"data":"{\"operationName\": \"Login\",\"variables\": {\"email\": \"{{account}}\",\"password\": \"{{password}}\"},\"query\": \"mutation Login($email: String!, $password: String!) {\\n  login(email: $email, password: $password) {\\n    uid\\n    name\\n    twoWay\\n    serverTime\\n    __typename\\n  }\\n}\"}"},"rule":{"success_asserts":[{"re":"200","from":"status"}],"failed_asserts":[],"extract_variables":[{"name":"cookie","re":"Set-Cookie:(.+?);","from":"header"}]}},{"comment":"签到","request":{"method":"POST","url":"https://api.lkong.com/api","headers":[{"name":"Host","value":"api.lkong.com"},{"name":"Connection","value":"keep-alive"},{"name":"Pragma","value":"no-cache"},{"name":"Cache-Control","value":"no-cache"},{"name":"sec-ch-ua","value":"\"Google Chrome\";v=\"93\", \" Not;A Brand\";v=\"99\", \"Chromium\";v=\"93\""},{"name":"accept","value":"*/*"},{"name":"content-type","value":"application/json"},{"name":"User-Agent","value":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36"},{"name":"sec-ch-ua-platform","value":"\"Windows\""},{"name":"Origin","value":"https://www.lkong.com"},{"name":"Referer","value":"https://www.lkong.com/"},{"name":"Accept-Encoding","value":"gzip, deflate, br"},{"name":"Accept-Language","value":"zh-CN,zh;q=0.9,en;q=0.8"},{"name":"Cookie","value":"{{cookie}}"}],"cookies":[],"data":"{\"variables\":{},\"query\":\"mutation {\\n  punch {\\n    uid\\n    punchday\\n    isPunch\\n    punchhighestday\\n    punchallday\\n    __typename\\n  }\\n}\\n\"}","mimeType":"application/json"},"rule":{"success_asserts":[{"re":"200","from":"status"}],"failed_asserts":[{"re":"\"uid\":0","from":"content"}],"extract_variables":[{"name":"uid","re":"\"uid\":(.+?),\"","from":"content"},{"name":"punchday","re":"\"punchday\":(.+?),\"","from":"content"},{"name":"punchhighestday","re":"\"punchhighestday\":(.+?),\"","from":"content"},{"name":"punchallday","re":"\"punchallday\":(.+?),\"","from":"content"}]}},{"comment":"登出","request":{"method":"POST","url":"https://api.lkong.com/api","headers":[{"name":"Content-Type","value":"application/json"},{"name":"Cookie","value":"{{cookie}}"}],"cookies":[],"data":"{\n    \"variables\": {},\n    \"query\": \"mutation {\\n  logout {\\n    ok\\n    __typename\\n  }\\n}\"\n}"},"rule":{"success_asserts":[{"re":"200","from":"status"}],"failed_asserts":[],"extract_variables":[]}},{"comment":"生成日志","request":{"method":"GET","url":"api://util/string/replace?r=text&t=%C2%A0&p=%C2%A0&s=%E7%94%A8%E6%88%B7ID%E4%B8%BA%EF%BC%9A{{uid|urlencode}}%EF%BC%8C%E5%BD%93%E5%89%8D%E7%AD%BE%E5%88%B0%EF%BC%9A{{punchday|urlencode}}%E5%A4%A9%EF%BC%8C%E6%9C%80%E9%AB%98%E7%AD%BE%E5%88%B0{{punchhighestday|urlencode}}%E5%A4%A9%EF%BC%8C%E6%80%BB%E5%85%B1%E7%AD%BE%E5%88%B0{{punchallday|urlencode}}%E5%A4%A9%E3%80%82","headers":[],"cookies":[]},"rule":{"success_asserts":[{"re":"200","from":"status"}],"failed_asserts":[],"extract_variables":[{"re":".+","from":"content","name":"__log__"}]}}]
> ```
> 
> @a76yyyy 

重新发起一个issue即可，发起并PR后我会把这个issue关闭
