### ISSUE TITLE
OpenFrp 评论区

### ISSUE THREAD

**Issue by ddd-zero** [qd-today/templates#155]

**Comment by yxkline** [comment]
2022-2-16 11:13:07 | 成功 | 签到成功，今天运气不错，获得了 3GB 流量，目前您的剩余流量为 9GB。
2022-2-16 11:11:11 | 成功 | <!DOCTYPE HTML>
2022-2-16 0:02:12 | 成功 | <!DOCTYPE HTML>
2022-2-15 10:51:43 | 成功 | 您今天已经签到过了，请明天再来
2022-2-15 10:28:28 | 成功 | 您今天已经签到过了，请明天再来
2022-2-15 10:28:25 | 成功 | 签到成功，这是你第一次签到，获得了 5GB 流量。
15日录入cookie，成功签到，16日签到就不成功了，第一遍手动登陆网站，提示reCaptcha失败，第二遍登陆成功，发现确实没签到，这时候去框架那运行，又正常了

**Comment by ddd-zero** [comment]
> ![image](https://user-images.githubusercontent.com/80211538/154212120-c411433b-41ea-4076-919e-071b4608a5f2.png) ![image](https://user-images.githubusercontent.com/80211538/154212367-8f6d0c92-705f-4914-a768-bf826daebef7.png) 15日录入cookie，成功签到，16日签到就不成功了，第一遍手动登陆网站，提示reCaptcha失败，第二遍登陆成功，发现确实没签到奖励，这时候去框架那运行，又正常了。（补充：原以为是隔天登陆才显示reCaptcha失败，刚刚去登，又这样，这才隔了几个小时）

我先测试一下。看着像是cookie过期了。这网站cookie一天就过期么。。

**Comment by ddd-zero** [comment]
> ![image](https://user-images.githubusercontent.com/80211538/154212120-c411433b-41ea-4076-919e-071b4608a5f2.png) ![image](https://user-images.githubusercontent.com/80211538/154212367-8f6d0c92-705f-4914-a768-bf826daebef7.png) 15日录入cookie，成功签到，16日签到就不成功了，第一遍手动登陆网站，提示reCaptcha失败，第二遍登陆成功，发现确实没签到奖励，这时候去框架那运行，又正常了。（补充：原以为是隔天登陆才显示reCaptcha失败，刚刚去登，又这样，这才隔了几个小时）

这家Cookie几个小时就过期。账号密码登录有校验，第二个校验加密了，我看不懂怎么解的。搞不定这玩意

**Comment by 17huiwei** [comment]
签到失效了，更新了cookies，做了实名认证，都不行。

Failed at 1/2 request,
Fail assert: {"re": "200", "from": "status"} from success_asserts,
Response Error : HTTP 503: Service Unavailable,
Request URL: https://www.openfrp.net/?page=panel&module=sign

**Comment by QYF233** [comment]
签到没用了，网站直接就没有cookie

**Comment by RUANRUI1995** [comment]
已经失效了

**Comment by Jerry-FaGe** [comment]
确实失效了

**Comment by amxoy** [comment]
不更新了吗？

**Comment by github-h** [comment]
同 #378 以后更新在那个issue里
