### ISSUE TITLE
腾讯视频VIP 评论区

### ISSUE THREAD

**Issue by AragonSnow** [qd-today/templates#30]

**Comment by mmkkllpp** [comment]
手机app抓包ck，签到一直失败，是失效了吗

**Comment by Tourist-0** [comment]
请问是不是需要用iPhone手机抓包才行？

**Comment by Acetaol** [comment]
一直失效 没法用啊

**Comment by dhbowen1** [comment]
抓了app的包，提示签到成功，实际没有成功

**Comment by nuoyi66** [comment]
现在签到日志一直是【随机获得1~99点V力值】   实际未成功
正常成功签到的日志是【已签到，获得xx点V力值】

**Comment by wildbull91** [comment]
用不了

**Comment by crossgg** [comment]
https://github.com/qd-today/templates/issues/683
