### ISSUE TITLE
2xfree 讨论区

### ISSUE THREAD

**Issue by IITII** [qd-today/templates#302]

**Comment by voodooTTC** [comment]
大佬~2xfree 签到变化了。求更新。

**Comment by IITII** [comment]
尊重站点意愿, 移除签到脚本. 活跃度有需求的话使用通用保号即可.

**Comment by voodooTTC** [comment]
> 尊重站点意愿, 移除签到脚本. 活跃度有需求的话使用通用保号即可.

我试了普通通用保号 和 CF通用保号 都不成功。
