### ISSUE TITLE
有制作模板需求的，请提交在这里。

### ISSUE THREAD

**Issue by jianglihzl** [qd-today/templates#498]
- 名称：KDSlife
- 类型：网站
- 网址：https://club.kdslife.com/
- 相关：无
- 描述：定期登陆就行了

谢谢！

**Comment by nodis** [comment]
名称：扫描全能王
类型：APP
网址：https://club.kdslife.com/
相关：无
描述：每日自动签到

**Comment by nodis** [comment]
名称：什么值得买
类型：网站
网址：https://www.smzdm.com/
相关：无
描述：每日自动签到

**Comment by r5h2y0** [comment]
- 名称：比亚迪海洋
- 类型：APP
- 网址：APP
- 相关：无
- 描述：我的-每日签到，7天、10天、20天、30天领取额外奖励

**Comment by Fallenathenaaa** [comment]
https://www.naiquan.me/

**Comment by Fallenathenaaa** [comment]
名称：奶圈
类型：网站
网址：https://www.naiquan.me/
相关：无
描述：自动签到获取积分
谢谢
