### ISSUE TITLE
搜书吧 评论区

### ISSUE THREAD

**Issue by loveqianool** [qd-today/templates#512]
### HAR 模板名称

搜书吧

### 作者信息

loveqianool

### 模板备注及说明

http://www.soushu555.org/
账户密码

### HAR 文件名

soushu555.org.har

### 其他信息

```Markdown
暂无
```

### HAR 模板内容

```JSON
[{"request":{"method":"GET","url":"{{Domain|default(\"http://www.soushu555.org/\")}}","headers":[],"cookies":[]},"rule":{"success_asserts":[{"re":"403","from":"status"},{"re":"200","from":"content"}],"failed_asserts":[],"extract_variables":[{"name":"Domain","re":"url=(.+)\"","from":"content"},{"name":"tid","re":"","from":"content"},{"name":"doid","re":"","from":"content"}]}},{"request":{"method":"GET","url":"{{ Domain }}","headers":[],"cookies":[]},"rule":{"success_asserts":[{"re":"200","from":"status"}],"failed_asserts":[],"extract_variables":[{"name":"Domain","re":"url=(.+)\"","from":"content"}]}},{"request":{"method":"GET","url":"{{ Domain }}","headers":[],"cookies":[]},"rule":{"success_asserts":[{"re":"404","from":"status"},{"re":"200","from":"content"}],"failed_asserts":[],"extract_variables":[{"name":"Domain","re":"href=\"(.+?)\"\\sclass=\"link\"","from":"content"}]}},{"request":{"method":"POST","url":"{{ Domain }}/member.php?mod=logging&action=login&loginsubmit=yes&inajax=1","headers":[],"cookies":[],"data":"username={{username}}&password={{password}}"},"rule":{"success_asserts":[{"re":"欢迎您回来","from":"content"}],"failed_asserts":[{"re":"error","from":"content"}],"extract_variables":[]}},{"request":{"method":"GET","url":"{{ Domain }}","headers":[],"cookies":[],"data":""},"rule":{"success_asserts":[{"re":"200","from":"status"}],"failed_asserts":[],"extract_variables":[{"name":"formhash","re":"formhash=(\\w+)\"","from":"content"},{"name":"tids","re":"/最新主题[\\s\\S]+?tid=(\\d+)[\\s\\S]+?tid=(\\d+)[\\s\\S]+?tid=(\\d+)[\\s\\S]+?(?<=valign=\\\"top\\\")/g","from":"content"}]}},{"comment":"循环开始","request":{"method":"GET","url":"{% for value in range(0, 5, 1) %}     ","headers":[],"cookies":[],"data":""},"rule":{"success_asserts":[{"re":"200","from":"status"}],"failed_asserts":[],"extract_variables":[]}},{"comment":"循环发表记录","request":{"method":"POST","url":"{{ Domain }}/home.php?mod=spacecp&ac=doing&view=me","headers":[],"cookies":[],"data":"message={{date_time(1,1,0)}}&add=&addsubmit=true&formhash={{formhash}}"},"rule":{"success_asserts":[{"re":"301","from":"status"}],"failed_asserts":[],"extract_variables":[]}},{"comment":"延时","request":{"method":"GET","url":"api://util/delay/20","headers":[],"cookies":[],"data":""},"rule":{"success_asserts":[{"re":"200","from":"status"}],"failed_asserts":[],"extract_variables":[]}},{"comment":"延时","request":{"method":"GET","url":"api://util/delay/20","headers":[],"cookies":[],"data":""},"rule":{"success_asserts":[{"re":"200","from":"status"}],"failed_asserts":[],"extract_variables":[]}},{"comment":"延时","request":{"method":"GET","url":"api://util/delay/21","headers":[],"cookies":[],"data":""},"rule":{"success_asserts":[{"re":"200","from":"status"}],"failed_asserts":[],"extract_variables":[]}},{"comment":"循环块结束","request":{"method":"GET","url":"{% endfor %}","headers":[],"cookies":[],"data":""},"rule":{"success_asserts":[],"failed_asserts":[],"extract_variables":[]}},{"comment":"","request":{"method":"GET","url":"{{ Domain }}/home.php?mod=space&do=doing&view=me&from=space","headers":[],"cookies":[],"data":""},"rule":{"success_asserts":[{"re":"200","from":"status"}],"failed_asserts":[],"extract_variables":[{"name":"doids","re":"/doid=(\\d+)/g","from":"content"}]}},{"comment":"循环开始","request":{"method":"GET","url":"{% for doid in doids %}","headers":[],"cookies":[],"data":""},"rule":{"success_asserts":[],"failed_asserts":[],"extract_variables":[]}},{"comment":"循环删除记录","request":{"method":"POST","url":"{{ Domain }}/home.php?mod=spacecp&ac=doing&op=delete&doid={{doid|urlencode}}","headers":[],"cookies":[],"data":"handlekey=register&formhash={{formhash}}&deletesubmit=true"},"rule":{"success_asserts":[{"re":"302","from":"status"}],"failed_asserts":[],"extract_variables":[]}},{"comment":"循环块结束","request":{"method":"GET","url":"{% endfor %}","headers":[],"cookies":[],"data":""},"rule":{"success_asserts":[]}},{"comment":"For 循环开始","request":{"method":"GET","url":"{% for tmplist in tids %}","headers":[],"cookies":[],"data":""},"rule":{"success_asserts":[],"failed_asserts":[],"extract_variables":[]}},{"comment":"For 循环开始","request":{"method":"GET","url":"{% for tid in tmplist %}","headers":[],"cookies":[],"data":""},"rule":{"success_asserts":[],"failed_asserts":[],"extract_variables":[]}},{"request":{"method":"POST","url":"{{ Domain }}/forum.php?mod=post&action=reply&fid=40&tid={{tid|urlencode}}&extra=&replysubmit=yes&infloat=yes&handlekey=fastpost&inajax=1","headers":[],"cookies":[],"data":"message=thx+up+share&formhash={{formhash}}"},"rule":{"success_asserts":[{"re":"回复发布成功","from":"content"},{"re":"504","from":"status"}],"failed_asserts":[],"extract_variables":[]}},{"comment":"延时","request":{"method":"GET","url":"api://util/delay/20","headers":[],"cookies":[],"data":""},"rule":{"success_asserts":[{"re":"200","from":"status"}],"failed_asserts":[],"extract_variables":[]}},{"comment":"延时","request":{"method":"GET","url":"api://util/delay/20","headers":[],"cookies":[],"data":""},"rule":{"success_asserts":[{"re":"200","from":"status"}],"failed_asserts":[],"extract_variables":[]}},{"comment":"延时","request":{"method":"GET","url":"api://util/delay/21","headers":[],"cookies":[],"data":""},"rule":{"success_asserts":[{"re":"200","from":"status"}],"failed_asserts":[],"extract_variables":[]}},{"comment":"For 循环结束","request":{"method":"GET","url":"{% endfor %}","headers":[],"cookies":[],"data":""},"rule":{"success_asserts":[],"failed_asserts":[],"extract_variables":[]}},{"comment":"For 循环结束","request":{"method":"GET","url":"{% endfor %}","headers":[],"cookies":[],"data":""},"rule":{"success_asserts":[]}},{"request":{"method":"GET","url":"{{ Domain }}/home.php?mod=spacecp&ac=credit&showcredit=1","headers":[],"cookies":[]},"rule":{"success_asserts":[{"re":"退出","from":"content"}],"failed_asserts":[],"extract_variables":[{"name":"yb","re":"(银币: </em>\\d+)","from":"content"},{"name":"yhz","re":"(用户组: .+?)<","from":"content"},{"name":"jf","re":"(积分: </em>\\d+)","from":"content"},{"name":"yhm","re":"访问我的空间\">(.+?)<","from":"content"}]}},{"comment":"Unicode转换","request":{"method":"POST","url":"api://util/unicode","headers":[],"cookies":[],"data":"html_unescape=false&content=用户名: {{yhm}} {{yhz}} {{jf | striptags}} {{yb | striptags}}"},"rule":{"success_asserts":[{"re":"200","from":"status"},{"re":"\"状态\": \"200\"","from":"content"}],"failed_asserts":[],"extract_variables":[{"name":"__log__","re":"\"转换后\": \"(.*)\"","from":"content"}]}}]
```

**Comment by zjc1972** [comment]
大佬求修复，现在的问题是soushu555.org用不了了，不过我换成soushu2025.com用邮箱登录可以

然后就是第18条（倒数8条）显示帖子被删了，无法回复，导致504，这个不知道怎么改

**Comment by wzgrx** [comment]
大佬只有www.sharp.allsou2024.com网站能访问
怎么修改网址啊
2024-03-03 16:00:16
日志：Failed at 1/25 request,
Fail assert: {"re": "url=", "from": "content"} from success_asserts,
Response Error : HTTP 301: Moved Permanently,
Request URL: {{ Domain | default("http://www.soushu555.org/") }}

**Comment by wzgrx** [comment]
> > 大佬只有www.sharp.allsou2024.com网站能访问 怎么修改网址啊 2024-03-03 16:00:16 日志：Failed at 1/25 request, Fail assert: {"re": "url=", "from": "content"} from success_asserts, Response Error : HTTP 301: Moved Permanently, Request URL: {{ Domain | default("http://www.soushu555.org/") }}
> 
> 手动更新试一下，公共模板有二十四小时左右的缓存，请在明后天更新公共模板后重新订阅。

好的，谢谢大佬

**Comment by Goldenbeef** [comment]
大佬，修改域名之后还是报错
Failed at 7/25 request,
Fail assert: {"re": "301", "from": "status"} from success_asserts,
Request URL: {{ Domain }}/home.php?mod=spacecp&ac=doing&view=me

**Comment by wzgrx** [comment]
Failed at 2/25 request,
Fail assert: {"re": "200", "from": "status"} from success_asserts,
Response Error : HTTP 599: quictls SSL_connect: SSL_ERROR_SYSCALL in connection to 345.allshu2024.com:8963 ,
Request URL: {{ Domain }}

**Comment by haofan170** [comment]
Failed at 7/25 request,
Fail assert: {"re": "301", "from": "status"} from success_asserts,
Request URL: {{ Domain }}/home.php?mod=spacecp&ac=doing&view=me
今天突然开始的 不知道什么情况

**Comment by Mr-Roxe** [comment]
?>=正则好像不支持，这是qd的问题，tids只能获取到最新帖子的第一个，然后遍历的时候，又获取不到了，空数组，对了，还有那个登录，好像用了js跳转，把第4个请求再发一遍就可以了，楼主加油，再改改。

**Comment by Mr-Roxe** [comment]
> > ?>=正则好像不支持，这是qd的问题，tids只能获取到最新帖子的第一个，然后遍历的时候，又获取不到了，空数组，对了，还有那个登录，好像用了js跳转，把第4个请求再发一遍就可以了，楼主加油，再改改。
> 
> 我这边一直在正常签呀，这个站经常连接不到数据库会导致失败，这个网站问题，您们先保证网络可用，网站正常打开，多试几次看看。

![2024-03-18_214623](https://github.com/qd-today/templates/assets/34638380/59ce1895-df75-49f4-8963-9fc719a23bde)

看吧，最新帖子不止一个吧，tids就一个元素，而且在遍历这个数组时，这元素都没取出来

![image](https://github.com/qd-today/templates/assets/34638380/c9b74ef9-2e93-4bf2-a81b-77b7e8d66ef6)

**Comment by wzgrx** [comment]
Failed at 2/25 request,
Fail assert: {"re": "200", "from": "status"} from success_asserts,
Response Error : HTTP 599: quictls SSL_connect: SSL_ERROR_SYSCALL in connection to 345.allshu2024.com:8963 ,
Request URL: {{ Domain }}

还是用不了，这个怎么自己改网址啊，他这个网址三天两头换几次，不然访问不了

**Comment by learningdog1** [comment]
用不了，希望能修复

**Comment by chenqs000** [comment]
Failed at 4/25 request,
Fail assert: {"re": "error", "from": "content"} from failed_asserts,
Request URL: {{ Domain }}/member.php?mod=logging&action=login&loginsubmit=yes&inajax=1

登录时报错了，确认过用户名和密码没有填错，也设置了代理。

**Comment by Mr-Roxe** [comment]
> Failed at 4/25 request, Fail assert: {"re": "error", "from": "content"} from failed_asserts, Request URL: {{ Domain }}/member.php?mod=logging&action=login&loginsubmit=yes&inajax=1
> 
> 登录时报错了，确认过用户名和密码没有填错，也设置了代理。

模板是能的，但是，有个小问题需要注意下，就是下面这里：
![image](https://github.com/qd-today/templates/assets/34638380/8454fb12-f3df-4090-a23a-110e8de06aa1)
请把网址后面的“/”去掉，就像我图中那样就行了，不出意外的话，就可以了

**Comment by chenqs000** [comment]
> > Failed at 4/25 request, Fail assert: {"re": "error", "from": "content"} from failed_asserts, Request URL: {{ Domain }}/member.php?mod=logging&action=login&loginsubmit=yes&inajax=1
> > 登录时报错了，确认过用户名和密码没有填错，也设置了代理。
> 
> 模板是能的，但是，有个小问题需要注意下，就是下面这里： ![image](https://private-user-images.githubusercontent.com/34638380/330379261-8454fb12-f3df-4090-a23a-110e8de06aa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTQwNjksIm5iZiI6MTcxNTY5Mzc2OSwicGF0aCI6Ii8zNDYzODM4MC8zMzAzNzkyNjEtODQ1NGZiMTItZjNkZi00MDkwLWEyM2EtMTEwZThkZTA2YWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDEzMzYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMzI5MGM3MjI0NzAwNGZmMGJlMjkwYWZhYTgzNTYyMTFmZWY3MWNlNDlkODkxODEzZTNmYWI1MTA5MmFkZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XG7Wzvd6epbAuJPqA9DQ0D-QFCag1BSFd9yoddVYpFU) 请把网址后面的“/”去掉，就像我图中那样就行了，不出意外的话，就可以了

还是不行，换成你图片的网址后报另外的错误，我用浏览器是能打开网站的
![image](https://github.com/qd-today/templates/assets/34451009/9fbd5fe1-721b-426b-b514-12ea4bc778ba)

![image](https://github.com/qd-today/templates/assets/34451009/4a76e152-76fa-43c3-b6dc-fe02d70b8404)

**Comment by chenqs000** [comment]
> > > Failed at 4/25 request, Fail assert: {"re": "error", "from": "content"} from failed_asserts, Request URL: {{ Domain }}/member.php?mod=logging&action=login&loginsubmit=yes&inajax=1
> > > 登录时报错了，确认过用户名和密码没有填错，也设置了代理。
> > 
> > 
> > 模板是能的，但是，有个小问题需要注意下，就是下面这里： ![image](https://private-user-images.githubusercontent.com/34638380/330379261-8454fb12-f3df-4090-a23a-110e8de06aa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTQwNjksIm5iZiI6MTcxNTY5Mzc2OSwicGF0aCI6Ii8zNDYzODM4MC8zMzAzNzkyNjEtODQ1NGZiMTItZjNkZi00MDkwLWEyM2EtMTEwZThkZTA2YWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDEzMzYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMzI5MGM3MjI0NzAwNGZmMGJlMjkwYWZhYTgzNTYyMTFmZWY3MWNlNDlkODkxODEzZTNmYWI1MTA5MmFkZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XG7Wzvd6epbAuJPqA9DQ0D-QFCag1BSFd9yoddVYpFU) 请把网址后面的“/”去掉，就像我图中那样就行了，不出意外的话，就可以了
> 
> 还是不行，换成你图片的网址后报另外的错误，我用浏览器是能打开网站的 ![image](https://private-user-images.githubusercontent.com/34451009/330462199-9fbd5fe1-721b-426b-b514-12ea4bc778ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzY4MzMsIm5iZiI6MTcxNTc3NjUzMywicGF0aCI6Ii8zNDQ1MTAwOS8zMzA0NjIxOTktOWZiZDVmZTEtNzIxYi00MjZiLWI1MTQtMTJlYTRiYzc3OGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDEyMzUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMWZjZTgxYTliZTI3YjBjNTNlYWUwZmJkNzUyM2QzZDRmNzg5NmZiODFiZmM3ZDAwOWQxNDZmNjRmNTkyY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4dQA7s4RHMlQbwc_mqJoWj19y15wXSQ-wBde6y95WFI)
> 
> ![image](https://private-user-images.githubusercontent.com/34451009/330461926-4a76e152-76fa-43c3-b6dc-fe02d70b8404.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzY4MzMsIm5iZiI6MTcxNTc3NjUzMywicGF0aCI6Ii8zNDQ1MTAwOS8zMzA0NjE5MjYtNGE3NmUxNTItNzZmYS00M2MzLWI2ZGMtZmUwMmQ3MGI4NDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDEyMzUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMjM0Y2Y0NzhlOGZiNWM1YWI0MjNiYzdjNzZmMjNlNTJjMWY4NWRhMTRjYjNjNGRhZGI3ZjFjYjZiMjM1N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NOAQf_yy0QkJ75qlQuqtuLboyx376lm2i8zItbZmJZk)

刚刚又试了下，居然成功了

**Comment by Mr-Roxe** [comment]
> > > > Failed at 4/25 request, Fail assert: {"re": "error", "from": "content"} from failed_asserts, Request URL: {{ Domain }}/member.php?mod=logging&action=login&loginsubmit=yes&inajax=1
> > > > 登录时报错了，确认过用户名和密码没有填错，也设置了代理。
> > > 
> > > 
> > > 模板是能的，但是，有个小问题需要注意下，就是下面这里： ![image](https://private-user-images.githubusercontent.com/34638380/330379261-8454fb12-f3df-4090-a23a-110e8de06aa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTQwNjksIm5iZiI6MTcxNTY5Mzc2OSwicGF0aCI6Ii8zNDYzODM4MC8zMzAzNzkyNjEtODQ1NGZiMTItZjNkZi00MDkwLWEyM2EtMTEwZThkZTA2YWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDEzMzYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMzI5MGM3MjI0NzAwNGZmMGJlMjkwYWZhYTgzNTYyMTFmZWY3MWNlNDlkODkxODEzZTNmYWI1MTA5MmFkZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XG7Wzvd6epbAuJPqA9DQ0D-QFCag1BSFd9yoddVYpFU) 请把网址后面的“/”去掉，就像我图中那样就行了，不出意外的话，就可以了
> > 
> > 
> > 还是不行，换成你图片的网址后报另外的错误，我用浏览器是能打开网站的 ![image](https://private-user-images.githubusercontent.com/34451009/330462199-9fbd5fe1-721b-426b-b514-12ea4bc778ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzY4MzMsIm5iZiI6MTcxNTc3NjUzMywicGF0aCI6Ii8zNDQ1MTAwOS8zMzA0NjIxOTktOWZiZDVmZTEtNzIxYi00MjZiLWI1MTQtMTJlYTRiYzc3OGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDEyMzUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMWZjZTgxYTliZTI3YjBjNTNlYWUwZmJkNzUyM2QzZDRmNzg5NmZiODFiZmM3ZDAwOWQxNDZmNjRmNTkyY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4dQA7s4RHMlQbwc_mqJoWj19y15wXSQ-wBde6y95WFI)
> > ![image](https://private-user-images.githubusercontent.com/34451009/330461926-4a76e152-76fa-43c3-b6dc-fe02d70b8404.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzY4MzMsIm5iZiI6MTcxNTc3NjUzMywicGF0aCI6Ii8zNDQ1MTAwOS8zMzA0NjE5MjYtNGE3NmUxNTItNzZmYS00M2MzLWI2ZGMtZmUwMmQ3MGI4NDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDEyMzUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMjM0Y2Y0NzhlOGZiNWM1YWI0MjNiYzdjNzZmMjNlNTJjMWY4NWRhMTRjYjNjNGRhZGI3ZjFjYjZiMjM1N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NOAQf_yy0QkJ75qlQuqtuLboyx376lm2i8zItbZmJZk)
> 
> 刚刚又试了下，居然成功了

![image](https://github.com/qd-today/templates/assets/34638380/10cc52f2-8fbd-49e5-8564-edc4faef427b)

它这应该是服务器的问题，有时是可以的

**Comment by 66kqkq** [comment]
搜书吧复活了，但是测试无法签到了。 挂了代理也不可以。
麻烦看下什么原因哈
2024-07-25 17:53:33
日志：Failed at 7/25 request,
Fail assert: {"re": "301", "from": "status"} from success_asserts,
Request URL: {{ Domain }}/home.php?mod=spacecp&ac=doing&view=me

**Comment by Mr-Roxe** [comment]
> HAR: 搜书吧 is invalid, close it.

![image](https://github.com/user-attachments/assets/fa59dc8e-fdc9-439b-a7f9-cf36ef3fdcdb)

今天可以了

**Comment by wzgrx** [comment]
失效了新网站
vsdf.n.rkggs5f4e5asf.com
