### ISSUE TITLE
福利江湖 评论区

### ISSUE THREAD

**Issue by loveqianool** [qd-today/templates#565]
### HAR 模板名称

福利江湖

### 作者信息

NSFW

### 模板备注及说明

https://fulijianghu.com
cookie 签到间隔填十分钟以内，可以挂在线时长。

### HAR 文件名

福利江湖.har

### HAR 模板内容

```JSON
[{"request":{"method":"GET","url":"https://fulijianghu.com/home.php?mod=space&do=profile","headers":[{"name":"cookie","value":"{{cookie}}"}],"cookies":[]},"rule":{"success_asserts":[{"re":"退出","from":"content"}],"failed_asserts":[{"re":"请先登录","from":"content"}],"extract_variables":[{"re":"(在线时间.+?)<","from":"content","name":"sj"},{"name":"u","re":"content=\"(.+)的个人资料\"","from":"content"},{"name":"g","re":">用户组&nbsp;:&nbsp;(.+?)<","from":"content"},{"name":"jf","re":"m>(积分</em>\\d+</li><li><em>金币</em>\\d+\\s)<","from":"content"}]}},{"comment":"Unicode转换","request":{"method":"POST","url":"api://util/unicode","headers":[],"cookies":[],"data":"html_unescape=false&content=用户名：{{u}} 用户组：{{g}} {{jf | striptags}} {{sj | striptags}}"},"rule":{"success_asserts":[{"re":"200","from":"status"},{"re":"\"状态\": \"200\"","from":"content"}],"failed_asserts":[],"extract_variables":[{"name":"__log__","re":"\"转换后\": \"(.*)\"","from":"content"}]}}]
```

**Comment by wzgrx** [comment]
Failed at 1/2 request,
Fail assert: {"re": "退出", "from": "content"} from success_asserts,
Response Error : HTTP 599: Connection timed out after 30001 milliseconds,
Request URL: https://fulijianghu.com/home.php?mod=space&do=profile

**Comment by a15355447898a** [comment]
```
Failed at 1/2 request,
Fail assert: {"re": "退出", "from": "content"} from success_asserts,
Response Error : HTTP 403: Forbidden,
Request URL: https://fulijianghu.com/home.php?mod=space&do=profile
```

![image](https://github.com/user-attachments/assets/f60d88f9-6604-4a62-9531-69b2c3e73750)
网站加上了cf,似乎得使用flaresolverr来解决

**Comment by jingyucang8** [comment]
想问下 签到间隔十分钟内怎么设置  啊

**Comment by zizaiweiwo** [comment]
> 想问下 签到间隔十分钟内怎么设置 啊
定时那选择，cron表达式，自己百度下如何写cron表达式

**Comment by kai456789** [comment]
2024-11-15 22:50:03
日誌：Failed at 1/2 request,
Fail assert: {"re": "退出", "from": "content"} from success_asserts,
Response Error : HTTP 403: Forbidden,
Request URL: https://fulijianghu.com/home.php?mod=space&do=profile

無法簽到
